Zymphonie theme
tiobeijo/ast-site pull request #16
Opened 2019-11-01 17:47 UTC by pedroluiz54

2019-11-02 18:23 UTC, edmargomes requested changes

2019-11-02 18:23 UTC, edmargomes commented on config/sync/ast_theme.settings.yml
> +  path: 'public://logo (cópia).PNG'
Ajustar o nome do arquivo. logo.png

2019-11-02 18:23 UTC, edmargomes commented on web/themes/custom/ast_theme/sass/media.scss
> +    max-width: 1240px;
Todo esses arquivos SCSS, 100% deles foram editados? Não poderia enviar somente a parte que editou, ou seja, somente a linha e a classe e não scss todo?

2019-11-04 17:23 UTC, pedroluiz54 commented on web/themes/custom/ast_theme/sass/media.scss
> +    max-width: 1240px;
Arquivos modificados.

2019-11-04 17:23 UTC, pedroluiz54 commented on config/sync/ast_theme.settings.yml
> +  path: 'public://logo (cópia).PNG'
Feito.

2019-11-05 11:15 UTC, edmargomes requested changes

2019-11-05 11:15 UTC, edmargomes commented on composer.json
> +    "drupal/core": "^8.7.0",
Itens estão se repetindo no arquivo

2019-11-05 11:15 UTC, edmargomes commented on config/sync/ast_theme.settings.yml
> +  path: 'public://logo (cópia).PNG'
Mas ainda esta _logo (cópia).PNG_

2019-11-05 16:32 UTC, edmargomes commented
Vamos criar um novo MR

2019-11-05 16:32 UTC, closed without merging